"""add active_task_id to exam_processing_links

Revision ID: 0716cd4353bb
Revises: a4fddeaa452d
Create Date: 2026-08-09 17:43:44.672926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0716cd4353bb'
down_revision: Union[str, None] = 'a4fddeaa452d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_processing_links', sa.Column('active_task_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_processing_links', 'active_task_id')
    # ### end Alembic commands ###
