"""add subject_codes to stations

Revision ID: 1a3040850851
Revises: 825110a1eb17
Create Date: 2026-08-05 03:38:32.437844
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1a3040850851'
down_revision: Union[str, None] = '825110a1eb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('subject_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'subject_codes')
    # ### end Alembic commands ###
