"""phase7 excel collection

Revision ID: 6346da621987
Revises: a84dacdafa1a
Create Date: 2026-07-27 09:24:18.791038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6346da621987'
down_revision: Union[str, None] = 'a84dacdafa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_workbooks',
    sa.Column('workbook_id', sa.String(length=80), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration_hash', sa.String(length=80), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_excel_workbooks_exam_id_exams')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_excel_workbooks_generated_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_excel_workbooks_school_id_schools')),
    sa.PrimaryKeyConstraint('workbook_id', name=op.f('pk_excel_workbooks'))
    )
    op.create_index(op.f('ix_excel_workbooks_exam_id'), 'excel_workbooks', ['exam_id'], unique=False)
    op.create_index(op.f('ix_excel_workbooks_school_id'), 'excel_workbooks', ['school_id'], unique=False)
    op.create_table('excel_import_batches',
    sa.Column('import_id', sa.String(length=80), nullable=False),
    sa.Column('workbook_id', sa.String(length=80), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name=op.f('fk_excel_import_batches_imported_by_users')),
    sa.ForeignKeyConstraint(['workbook_id'], ['excel_workbooks.workbook_id'], name=op.f('fk_excel_import_batches_workbook_id_excel_workbooks')),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk_excel_import_batches')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_excel_import_batches_idempotency_key'))
    )
    op.create_index(op.f('ix_excel_import_batches_workbook_id'), 'excel_import_batches', ['workbook_id'], unique=False)
    op.create_table('excel_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.String(length=80), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=60), nullable=True),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('paper_type', sa.String(length=20), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['excel_import_batches.import_id'], name=op.f('fk_excel_import_rows_import_id_excel_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excel_import_rows')),
    sa.UniqueConstraint('import_id', 'row_no', name='uq_excel_import_rows_import_row')
    )
    op.create_index(op.f('ix_excel_import_rows_import_id'), 'excel_import_rows', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excel_import_rows_import_id'), table_name='excel_import_rows')
    op.drop_table('excel_import_rows')
    op.drop_index(op.f('ix_excel_import_batches_workbook_id'), table_name='excel_import_batches')
    op.drop_table('excel_import_batches')
    op.drop_index(op.f('ix_excel_workbooks_school_id'), table_name='excel_workbooks')
    op.drop_index(op.f('ix_excel_workbooks_exam_id'), table_name='excel_workbooks')
    op.drop_table('excel_workbooks')
    # ### end Alembic commands ###
