"""phase3 attendance incidents marks

Revision ID: 7738c7d5c366
Revises: b98b4d7e3975
Create Date: 2026-07-27 08:37:34.798700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = '7738c7d5c366'
down_revision: Union[str, None] = 'b98b4d7e3975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark_batch_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('payload_hash', sa.String(length=80), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_mark_batch_receipts_actor_id_users')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_mark_batch_receipts_exam_id_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mark_batch_receipts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_mark_batch_receipts_idempotency_key'))
    )
    op.create_index(op.f('ix_mark_batch_receipts_exam_id'), 'mark_batch_receipts', ['exam_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_student_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('INVIGILATOR_ISAL_TRANSCRIPTION', 'SUPERVISOR_CAL_TRANSCRIPTION', name='attendance_source', native_enum=False, length=60), nullable=False),
    sa.Column('transcribed_by', sa.Integer(), nullable=True),
    sa.Column('transcribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_student_subject_id'], ['exam_student_subjects.id'], name=op.f('fk_attendance_exam_student_subject_id_exam_student_subjects')),
    sa.ForeignKeyConstraint(['transcribed_by'], ['users.id'], name=op.f('fk_attendance_transcribed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('exam_student_subject_id', 'paper_type', name='uq_attendance_ess_paper')
    )
    op.create_index(op.f('ix_attendance_exam_student_subject_id'), 'attendance', ['exam_student_subject_id'], unique=False)
    op.create_table('exam_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('exam_student_subject_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('exam_subject_id', sa.Integer(), nullable=True),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('incident_type', sa.Enum('MISSING_SCRIPT', 'ATTENDANCE_MISMATCH', 'ILLNESS_OR_DISTURBANCE', 'OTHER', name='incident_type', native_enum=False, length=40), nullable=False),
    sa.Column('documented_in_supervisor_cal', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', name='incident_status', native_enum=False, length=20), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_incidents_exam_id_exams')),
    sa.ForeignKeyConstraint(['exam_student_subject_id'], ['exam_student_subjects.id'], name=op.f('fk_exam_incidents_exam_student_subject_id_exam_student_subjects')),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_exam_incidents_exam_subject_id_exam_subjects')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_exam_incidents_raised_by_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_exam_incidents_resolved_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_exam_incidents_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_incidents'))
    )
    op.create_index(op.f('ix_exam_incidents_exam_id'), 'exam_incidents', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_incidents_exam_student_subject_id'), 'exam_incidents', ['exam_student_subject_id'], unique=False)
    op.create_index(op.f('ix_exam_incidents_exam_subject_id'), 'exam_incidents', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_exam_incidents_school_id'), 'exam_incidents', ['school_id'], unique=False)
    op.create_table('total_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_student_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('total_marks_obtained', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_total_marks_entered_by_users')),
    sa.ForeignKeyConstraint(['exam_student_subject_id'], ['exam_student_subjects.id'], name=op.f('fk_total_marks_exam_student_subject_id_exam_student_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_total_marks')),
    sa.UniqueConstraint('exam_student_subject_id', 'paper_type', name='uq_total_marks_ess_paper')
    )
    op.create_index(op.f('ix_total_marks_exam_student_subject_id'), 'total_marks', ['exam_student_subject_id'], unique=False)
    op.create_table('item_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_student_subject_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_item_marks_entered_by_users')),
    sa.ForeignKeyConstraint(['exam_student_subject_id'], ['exam_student_subjects.id'], name=op.f('fk_item_marks_exam_student_subject_id_exam_student_subjects')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_item_marks_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_marks')),
    sa.UniqueConstraint('exam_student_subject_id', 'question_id', name='uq_item_marks_ess_question')
    )
    op.create_index(op.f('ix_item_marks_exam_student_subject_id'), 'item_marks', ['exam_student_subject_id'], unique=False)
    op.create_index(op.f('ix_item_marks_question_id'), 'item_marks', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_marks_question_id'), table_name='item_marks')
    op.drop_index(op.f('ix_item_marks_exam_student_subject_id'), table_name='item_marks')
    op.drop_table('item_marks')
    op.drop_index(op.f('ix_total_marks_exam_student_subject_id'), table_name='total_marks')
    op.drop_table('total_marks')
    op.drop_index(op.f('ix_exam_incidents_school_id'), table_name='exam_incidents')
    op.drop_index(op.f('ix_exam_incidents_exam_subject_id'), table_name='exam_incidents')
    op.drop_index(op.f('ix_exam_incidents_exam_student_subject_id'), table_name='exam_incidents')
    op.drop_index(op.f('ix_exam_incidents_exam_id'), table_name='exam_incidents')
    op.drop_table('exam_incidents')
    op.drop_index(op.f('ix_attendance_exam_student_subject_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_mark_batch_receipts_exam_id'), table_name='mark_batch_receipts')
    op.drop_table('mark_batch_receipts')
    # ### end Alembic commands ###
