"""initial registry and users schema

Revision ID: 8190d1100c1d
Revises: 
Create Date: 2026-07-27 08:21:39.189861
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8190d1100c1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_levels')),
    sa.UniqueConstraint('name', name=op.f('uq_exam_levels_name'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'SYSTEM_ADMIN', 'REO', 'RAO', 'DEO', 'DAO', 'REGION_ITS', 'COUNCIL_ITS', 'SCHOOL_HEAD', name='standing_role_name', native_enum=False, length=40), nullable=False),
    sa.Column('scope_level', sa.Enum('GLOBAL', 'REGION', 'COUNCIL', 'SCHOOL', name='role_scope_level', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_olevel', sa.Boolean(), nullable=False),
    sa.Column('is_alevel', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('has_theory2', sa.Boolean(), nullable=False),
    sa.Column('has_practical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    op.create_table('councils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_councils_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_councils')),
    sa.UniqueConstraint('name', name=op.f('uq_councils_name'))
    )
    op.create_index(op.f('ix_councils_region_id'), 'councils', ['region_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('council_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_boards_council_id_councils')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_boards_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boards'))
    )
    op.create_index(op.f('ix_boards_council_id'), 'boards', ['council_id'], unique=False)
    op.create_index(op.f('ix_boards_region_id'), 'boards', ['region_id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_wards_council_id_councils')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wards')),
    sa.UniqueConstraint('council_id', 'name', name='uq_wards_council_id_name')
    )
    op.create_index(op.f('ix_wards_council_id'), 'wards', ['council_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centre_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('school_type', sa.Enum('GOVERNMENT', 'PRIVATE', 'UNKNOWN', name='school_type', native_enum=False, length=40), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('council_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('can_download_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_schools_council_id_councils')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_schools_region_id_regions')),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('fk_schools_ward_id_wards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('centre_number', name=op.f('uq_schools_centre_number'))
    )
    op.create_index(op.f('ix_schools_council_id'), 'schools', ['council_id'], unique=False)
    op.create_index(op.f('ix_schools_region_id'), 'schools', ['region_id'], unique=False)
    op.create_index(op.f('ix_schools_ward_id'), 'schools', ['ward_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', name='sex', native_enum=False, length=40), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('council_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_users_council_id_councils')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_users_region_id_regions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_council_id'), 'users', ['council_id'], unique=False)
    op.create_index(op.f('ix_users_region_id'), 'users', ['region_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_region_id'), table_name='users')
    op.drop_index(op.f('ix_users_council_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_ward_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_region_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_council_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_wards_council_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_boards_region_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_council_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_councils_region_id'), table_name='councils')
    op.drop_table('councils')
    op.drop_table('subjects')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('exam_levels')
    # ### end Alembic commands ###
