"""add is_primary is_olevel is_alevel to schools

Revision ID: 91012f76325c
Revises: cb67105909f7
Create Date: 2026-08-03 15:19:33.796536
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91012f76325c'
down_revision: Union[str, None] = 'cb67105909f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('schools', sa.Column('is_olevel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('schools', sa.Column('is_alevel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'is_alevel')
    op.drop_column('schools', 'is_olevel')
    op.drop_column('schools', 'is_primary')
    # ### end Alembic commands ###
