"""add_collection_push_cache

Revision ID: a4fddeaa452d
Revises: 1a3040850851
Create Date: 2026-08-05 09:46:19.568118
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4fddeaa452d'
down_revision: Union[str, None] = '1a3040850851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_push_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('centre_number', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=40), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('paper_type', sa.String(length=20), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('push_task_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_collection_push_cache_exam_id_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_push_cache')),
    sa.UniqueConstraint('exam_id', 'entity_type', 'centre_number', 'student_id', 'subject_code', 'paper_type', name='uq_push_cache_row')
    )
    op.create_index(op.f('ix_collection_push_cache_exam_id'), 'collection_push_cache', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_push_cache_exam_id'), table_name='collection_push_cache')
    op.drop_table('collection_push_cache')
    # ### end Alembic commands ###
