"""phase4 station packages and sync bookkeeping

Revision ID: a84dacdafa1a
Revises: 7738c7d5c366
Create Date: 2026-07-27 08:46:41.617974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = 'a84dacdafa1a'
down_revision: Union[str, None] = '7738c7d5c366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_packages',
    sa.Column('package_id', sa.String(length=80), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('package_version', sa.Integer(), nullable=False),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('software_min_version', sa.String(length=20), nullable=False),
    sa.Column('configuration_hash', sa.String(length=80), nullable=False),
    sa.Column('assigned_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_station_packages_exam_id_exams')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_packages_station_id_stations')),
    sa.PrimaryKeyConstraint('package_id', name=op.f('pk_station_packages')),
    sa.UniqueConstraint('station_id', 'package_version', name='uq_station_packages_station_version')
    )
    op.create_index(op.f('ix_station_packages_exam_id'), 'station_packages', ['exam_id'], unique=False)
    op.create_index(op.f('ix_station_packages_station_id'), 'station_packages', ['station_id'], unique=False)
    op.create_table('station_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.String(length=80), nullable=False),
    sa.Column('pending_events', sa.Integer(), nullable=False),
    sa.Column('rejected_events', sa.Integer(), nullable=False),
    sa.Column('local_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('central_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'MISMATCHED', name='reconciliation_status', native_enum=False, length=20), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['station_packages.package_id'], name=op.f('fk_station_reconciliations_package_id_station_packages')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_reconciliations_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_reconciliations'))
    )
    op.create_index(op.f('ix_station_reconciliations_package_id'), 'station_reconciliations', ['package_id'], unique=False)
    op.create_index(op.f('ix_station_reconciliations_station_id'), 'station_reconciliations', ['station_id'], unique=False)
    op.create_table('station_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.String(length=80), nullable=False),
    sa.Column('authorized_by', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], name=op.f('fk_station_sync_logs_authorized_by_users')),
    sa.ForeignKeyConstraint(['package_id'], ['station_packages.package_id'], name=op.f('fk_station_sync_logs_package_id_station_packages')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_sync_logs_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_sync_logs'))
    )
    op.create_index(op.f('ix_station_sync_logs_package_id'), 'station_sync_logs', ['package_id'], unique=False)
    op.create_index(op.f('ix_station_sync_logs_station_id'), 'station_sync_logs', ['station_id'], unique=False)
    op.create_table('sync_event_receipts',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'DUPLICATE', 'REJECTED', name='event_status', native_enum=False, length=20), nullable=False),
    sa.Column('rejection_code', sa.String(length=60), nullable=True),
    sa.Column('payload_hash', sa.String(length=80), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['station_packages.package_id'], name=op.f('fk_sync_event_receipts_package_id_station_packages')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_sync_event_receipts_station_id_stations')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_sync_event_receipts'))
    )
    op.create_index(op.f('ix_sync_event_receipts_package_id'), 'sync_event_receipts', ['package_id'], unique=False)
    op.create_index(op.f('ix_sync_event_receipts_station_id'), 'sync_event_receipts', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_event_receipts_station_id'), table_name='sync_event_receipts')
    op.drop_index(op.f('ix_sync_event_receipts_package_id'), table_name='sync_event_receipts')
    op.drop_table('sync_event_receipts')
    op.drop_index(op.f('ix_station_sync_logs_station_id'), table_name='station_sync_logs')
    op.drop_index(op.f('ix_station_sync_logs_package_id'), table_name='station_sync_logs')
    op.drop_table('station_sync_logs')
    op.drop_index(op.f('ix_station_reconciliations_station_id'), table_name='station_reconciliations')
    op.drop_index(op.f('ix_station_reconciliations_package_id'), table_name='station_reconciliations')
    op.drop_table('station_reconciliations')
    op.drop_index(op.f('ix_station_packages_station_id'), table_name='station_packages')
    op.drop_index(op.f('ix_station_packages_exam_id'), table_name='station_packages')
    op.drop_table('station_packages')
    # ### end Alembic commands ###
