"""phase2 exam config and role model

Revision ID: b98b4d7e3975
Revises: 8190d1100c1d
Create Date: 2026-07-27 08:27:48.647625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = 'b98b4d7e3975'
down_revision: Union[str, None] = '8190d1100c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('phase', sa.Enum('REGISTRATION', 'ENTRY_OPEN', 'ENTRY_LOCKED', 'PROCESSING', 'RESULTS_PUBLISHED', 'ARCHIVED', name='exam_phase', native_enum=False, length=40), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_configuration_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_exams_board_id_boards')),
    sa.ForeignKeyConstraint(['level_id'], ['exam_levels.id'], name=op.f('fk_exams_level_id_exam_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams')),
    sa.UniqueConstraint('name', name=op.f('uq_exams_name'))
    )
    op.create_index(op.f('ix_exams_board_id'), 'exams', ['board_id'], unique=False)
    op.create_index(op.f('ix_exams_level_id'), 'exams', ['level_id'], unique=False)
    op.create_table('exam_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_schools_exam_id_exams')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_exam_schools_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_schools')),
    sa.UniqueConstraint('exam_id', 'school_id', name='uq_exam_schools_exam_id_school_id')
    )
    op.create_index(op.f('ix_exam_schools_exam_id'), 'exam_schools', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_schools_school_id'), 'exam_schools', ['school_id'], unique=False)
    op.create_table('exam_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=60), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', name='sex', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_students_exam_id_exams')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_exam_students_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_students')),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_students_exam_id_student_id')
    )
    op.create_index(op.f('ix_exam_students_exam_id'), 'exam_students', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_students_school_id'), 'exam_students', ['school_id'], unique=False)
    op.create_table('exam_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('has_theory2', sa.Boolean(), nullable=False),
    sa.Column('has_practical', sa.Boolean(), nullable=False),
    sa.Column('total_marks_theory1', sa.Integer(), nullable=False),
    sa.Column('total_marks_theory2', sa.Integer(), nullable=False),
    sa.Column('total_marks_practical', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_subjects_exam_id_exams')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exam_subjects_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_subjects')),
    sa.UniqueConstraint('exam_id', 'subject_id', name='uq_exam_subjects_exam_id_subject_id')
    )
    op.create_index(op.f('ix_exam_subjects_exam_id'), 'exam_subjects', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_subjects_subject_id'), 'exam_subjects', ['subject_id'], unique=False)
    op.create_table('exam_configuration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=80), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sealed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_configuration_versions_exam_id_exams')),
    sa.ForeignKeyConstraint(['sealed_by'], ['users.id'], name=op.f('fk_exam_configuration_versions_sealed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_configuration_versions')),
    sa.UniqueConstraint('exam_id', 'version', name='uq_exam_config_versions_exam_version')
    )
    op.create_index(op.f('ix_exam_configuration_versions_exam_id'), 'exam_configuration_versions', ['exam_id'], unique=False)
    op.create_table('exam_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('EXAM_ADMIN', 'REGIONAL_EXAM_REP', 'COUNCIL_EXAM_REP', 'DATA_ENTERER', name='exam_role_name', native_enum=False, length=40), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('council_id', sa.Integer(), nullable=True),
    sa.Column('appointed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointed_by'], ['users.id'], name=op.f('fk_exam_role_assignments_appointed_by_users')),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_exam_role_assignments_council_id_councils')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_role_assignments_exam_id_exams')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_exam_role_assignments_region_id_regions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_role_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_role_assignments')),
    sa.UniqueConstraint('exam_id', 'user_id', 'role', name='uq_exam_role_assignments_exam_user_role')
    )
    op.create_index(op.f('ix_exam_role_assignments_council_id'), 'exam_role_assignments', ['council_id'], unique=False)
    op.create_index(op.f('ix_exam_role_assignments_exam_id'), 'exam_role_assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_role_assignments_region_id'), 'exam_role_assignments', ['region_id'], unique=False)
    op.create_index(op.f('ix_exam_role_assignments_user_id'), 'exam_role_assignments', ['user_id'], unique=False)
    op.create_table('exam_student_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_student_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_student_id'], ['exam_students.id'], name=op.f('fk_exam_student_subjects_exam_student_id_exam_students')),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_exam_student_subjects_exam_subject_id_exam_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_student_subjects')),
    sa.UniqueConstraint('exam_student_id', 'exam_subject_id', name='uq_exam_student_subjects_student_subject')
    )
    op.create_index(op.f('ix_exam_student_subjects_exam_student_id'), 'exam_student_subjects', ['exam_student_id'], unique=False)
    op.create_index(op.f('ix_exam_student_subjects_exam_subject_id'), 'exam_student_subjects', ['exam_subject_id'], unique=False)
    op.create_table('finalized_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('writer_mode', sa.Enum('ONLINE', 'STATION', 'EXCEL', name='writer_mode', native_enum=False, length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('completion_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_finalized_scopes_exam_id_exams')),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_finalized_scopes_exam_subject_id_exam_subjects')),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], name=op.f('fk_finalized_scopes_finalized_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_finalized_scopes_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finalized_scopes')),
    sa.UniqueConstraint('exam_id', 'school_id', 'exam_subject_id', 'paper_type', name='uq_finalized_scopes_scope')
    )
    op.create_index(op.f('ix_finalized_scopes_exam_id'), 'finalized_scopes', ['exam_id'], unique=False)
    op.create_index(op.f('ix_finalized_scopes_exam_subject_id'), 'finalized_scopes', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_finalized_scopes_school_id'), 'finalized_scopes', ['school_id'], unique=False)
    op.create_table('question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('instruction', sa.String(length=255), nullable=True),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_question_groups_exam_subject_id_exam_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_groups')),
    sa.UniqueConstraint('exam_subject_id', 'paper_type', 'code', name='uq_question_groups_subject_paper_code')
    )
    op.create_index(op.f('ix_question_groups_exam_subject_id'), 'question_groups', ['exam_subject_id'], unique=False)
    op.create_table('scope_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_scope_revisions_actor_id_users')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_scope_revisions_exam_id_exams')),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_scope_revisions_exam_subject_id_exam_subjects')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_scope_revisions_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_revisions'))
    )
    op.create_index(op.f('ix_scope_revisions_exam_id'), 'scope_revisions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_scope_revisions_exam_subject_id'), 'scope_revisions', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_scope_revisions_school_id'), 'scope_revisions', ['school_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('station_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('council_id', sa.Integer(), nullable=True),
    sa.Column('managed_by', sa.Integer(), nullable=True),
    sa.Column('sync_key_hash', sa.String(length=255), nullable=True),
    sa.Column('software_version', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['councils.id'], name=op.f('fk_stations_council_id_councils')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_stations_exam_id_exams')),
    sa.ForeignKeyConstraint(['managed_by'], ['users.id'], name=op.f('fk_stations_managed_by_users')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_stations_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations')),
    sa.UniqueConstraint('station_code', name=op.f('uq_stations_station_code'))
    )
    op.create_index(op.f('ix_stations_exam_id'), 'stations', ['exam_id'], unique=False)
    op.create_table('data_enterer_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_role_assignment_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_role_assignment_id'], ['exam_role_assignments.id'], name=op.f('fk_data_enterer_scopes_exam_role_assignment_id_exam_role_assignments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_data_enterer_scopes_school_id_schools')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_data_enterer_scopes_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_enterer_scopes'))
    )
    op.create_index(op.f('ix_data_enterer_scopes_exam_role_assignment_id'), 'data_enterer_scopes', ['exam_role_assignment_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('question_number', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_questions_exam_subject_id_exam_subjects')),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.id'], name=op.f('fk_questions_group_id_question_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('exam_subject_id', 'paper_type', 'question_number', name='uq_questions_subject_paper_qnum')
    )
    op.create_index(op.f('ix_questions_exam_subject_id'), 'questions', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_questions_group_id'), 'questions', ['group_id'], unique=False)
    op.create_table('scope_write_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.Enum('THEORY1', 'THEORY2', 'PRACTICAL', 'ALL', name='paper_type', native_enum=False, length=20), nullable=False),
    sa.Column('writer_mode', sa.Enum('ONLINE', 'STATION', 'EXCEL', name='writer_mode', native_enum=False, length=40), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_scope_write_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_scope_write_assignments_exam_id_exams')),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name=op.f('fk_scope_write_assignments_exam_subject_id_exam_subjects')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_scope_write_assignments_school_id_schools')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_scope_write_assignments_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_write_assignments')),
    sa.UniqueConstraint('exam_id', 'school_id', 'exam_subject_id', 'paper_type', name='uq_scope_write_assignments_scope')
    )
    op.create_index(op.f('ix_scope_write_assignments_exam_id'), 'scope_write_assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_scope_write_assignments_exam_subject_id'), 'scope_write_assignments', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_scope_write_assignments_school_id'), 'scope_write_assignments', ['school_id'], unique=False)
    op.create_table('station_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_role_assignment_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_role_assignment_id'], ['exam_role_assignments.id'], name=op.f('fk_station_credentials_exam_role_assignment_id_exam_role_assignments')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_credentials_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_credentials'))
    )
    op.create_index(op.f('ix_station_credentials_exam_role_assignment_id'), 'station_credentials', ['exam_role_assignment_id'], unique=False)
    op.create_index(op.f('ix_station_credentials_station_id'), 'station_credentials', ['station_id'], unique=False)
    op.create_table('question_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_topics_question_id_questions')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_question_topics_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_topics')),
    sa.UniqueConstraint('question_id', 'topic_id', name='uq_question_topics_question_topic')
    )
    op.create_index(op.f('ix_question_topics_question_id'), 'question_topics', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_topics_topic_id'), 'question_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_topics_topic_id'), table_name='question_topics')
    op.drop_index(op.f('ix_question_topics_question_id'), table_name='question_topics')
    op.drop_table('question_topics')
    op.drop_index(op.f('ix_station_credentials_station_id'), table_name='station_credentials')
    op.drop_index(op.f('ix_station_credentials_exam_role_assignment_id'), table_name='station_credentials')
    op.drop_table('station_credentials')
    op.drop_index(op.f('ix_scope_write_assignments_school_id'), table_name='scope_write_assignments')
    op.drop_index(op.f('ix_scope_write_assignments_exam_subject_id'), table_name='scope_write_assignments')
    op.drop_index(op.f('ix_scope_write_assignments_exam_id'), table_name='scope_write_assignments')
    op.drop_table('scope_write_assignments')
    op.drop_index(op.f('ix_questions_group_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_subject_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_data_enterer_scopes_exam_role_assignment_id'), table_name='data_enterer_scopes')
    op.drop_table('data_enterer_scopes')
    op.drop_index(op.f('ix_stations_exam_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_scope_revisions_school_id'), table_name='scope_revisions')
    op.drop_index(op.f('ix_scope_revisions_exam_subject_id'), table_name='scope_revisions')
    op.drop_index(op.f('ix_scope_revisions_exam_id'), table_name='scope_revisions')
    op.drop_table('scope_revisions')
    op.drop_index(op.f('ix_question_groups_exam_subject_id'), table_name='question_groups')
    op.drop_table('question_groups')
    op.drop_index(op.f('ix_finalized_scopes_school_id'), table_name='finalized_scopes')
    op.drop_index(op.f('ix_finalized_scopes_exam_subject_id'), table_name='finalized_scopes')
    op.drop_index(op.f('ix_finalized_scopes_exam_id'), table_name='finalized_scopes')
    op.drop_table('finalized_scopes')
    op.drop_index(op.f('ix_exam_student_subjects_exam_subject_id'), table_name='exam_student_subjects')
    op.drop_index(op.f('ix_exam_student_subjects_exam_student_id'), table_name='exam_student_subjects')
    op.drop_table('exam_student_subjects')
    op.drop_index(op.f('ix_exam_role_assignments_user_id'), table_name='exam_role_assignments')
    op.drop_index(op.f('ix_exam_role_assignments_region_id'), table_name='exam_role_assignments')
    op.drop_index(op.f('ix_exam_role_assignments_exam_id'), table_name='exam_role_assignments')
    op.drop_index(op.f('ix_exam_role_assignments_council_id'), table_name='exam_role_assignments')
    op.drop_table('exam_role_assignments')
    op.drop_index(op.f('ix_exam_configuration_versions_exam_id'), table_name='exam_configuration_versions')
    op.drop_table('exam_configuration_versions')
    op.drop_index(op.f('ix_exam_subjects_subject_id'), table_name='exam_subjects')
    op.drop_index(op.f('ix_exam_subjects_exam_id'), table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index(op.f('ix_exam_students_school_id'), table_name='exam_students')
    op.drop_index(op.f('ix_exam_students_exam_id'), table_name='exam_students')
    op.drop_table('exam_students')
    op.drop_index(op.f('ix_exam_schools_school_id'), table_name='exam_schools')
    op.drop_index(op.f('ix_exam_schools_exam_id'), table_name='exam_schools')
    op.drop_table('exam_schools')
    op.drop_index(op.f('ix_exams_level_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_board_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
