"""phase8 collection closeout and export

Revision ID: c6c9107e7a65
Revises: 6346da621987
Create Date: 2026-07-27 09:36:34.365318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = 'c6c9107e7a65'
down_revision: Union[str, None] = '6346da621987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_readiness_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('closeout_revision', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_collection_readiness_runs_exam_id_exams')),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], name=op.f('fk_collection_readiness_runs_run_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_readiness_runs'))
    )
    op.create_index(op.f('ix_collection_readiness_runs_exam_id'), 'collection_readiness_runs', ['exam_id'], unique=False)
    op.create_table('collection_snapshots',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('exam_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('closeout_revision', sa.Integer(), nullable=False),
    sa.Column('configuration_version', sa.Integer(), nullable=True),
    sa.Column('configuration_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('sealed_by', sa.Integer(), nullable=True),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_collection_snapshots_exam_id_exams')),
    sa.ForeignKeyConstraint(['sealed_by'], ['users.id'], name=op.f('fk_collection_snapshots_sealed_by_users')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_collection_snapshots')),
    sa.UniqueConstraint('exam_id', 'closeout_revision', 'configuration_hash', name='uq_collection_snapshots_exam_rev_hash')
    )
    op.create_index(op.f('ix_collection_snapshots_exam_id'), 'collection_snapshots', ['exam_id'], unique=False)
    op.create_table('collection_export_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['collection_snapshots.snapshot_id'], name=op.f('fk_collection_export_files_snapshot_id_collection_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_export_files'))
    )
    op.create_index(op.f('ix_collection_export_files_snapshot_id'), 'collection_export_files', ['snapshot_id'], unique=False)
    op.add_column('exams', sa.Column('closeout_revision', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'closeout_revision')
    op.drop_index(op.f('ix_collection_export_files_snapshot_id'), table_name='collection_export_files')
    op.drop_table('collection_export_files')
    op.drop_index(op.f('ix_collection_snapshots_exam_id'), table_name='collection_snapshots')
    op.drop_table('collection_snapshots')
    op.drop_index(op.f('ix_collection_readiness_runs_exam_id'), table_name='collection_readiness_runs')
    op.drop_table('collection_readiness_runs')
    # ### end Alembic commands ###
