"""add station scope fields and station_schools table

Revision ID: cb67105909f7
Revises: feaf44d90bf7
Create Date: 2026-08-03 12:57:49.971541
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb67105909f7'
down_revision: Union[str, None] = 'feaf44d90bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_station_schools_school_id_schools')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_schools_station_id_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_schools')),
    sa.UniqueConstraint('station_id', 'school_id', name='uq_station_schools_station_school')
    )
    op.create_index(op.f('ix_station_schools_school_id'), 'station_schools', ['school_id'], unique=False)
    op.create_index(op.f('ix_station_schools_station_id'), 'station_schools', ['station_id'], unique=False)
    op.add_column('stations', sa.Column('scope_mode', sa.String(length=20), nullable=True))
    op.add_column('stations', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_stations_ward_id_wards'), 'stations', 'wards', ['ward_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stations_ward_id_wards'), 'stations', type_='foreignkey')
    op.drop_column('stations', 'ward_id')
    op.drop_column('stations', 'scope_mode')
    op.drop_index(op.f('ix_station_schools_station_id'), table_name='station_schools')
    op.drop_index(op.f('ix_station_schools_school_id'), table_name='station_schools')
    op.drop_table('station_schools')
    # ### end Alembic commands ###
