"""marks_audit_and_station_occurred_at

Revision ID: feaf44d90bf7
Revises: 9b8f664039ac
Create Date: 2026-08-03 11:58:04.906006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'feaf44d90bf7'
down_revision: Union[str, None] = '9b8f664039ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exam_student_subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('before_total', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('before_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_total', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('after_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('station_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('central_received_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('sync_event_id', sa.String(length=80), nullable=True),
    sa.Column('actor_assignment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_marks_audit_exam_id_exams')),
    sa.ForeignKeyConstraint(['exam_student_subject_id'], ['exam_student_subjects.id'], name=op.f('fk_marks_audit_exam_student_subject_id_exam_student_subjects')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_marks_audit_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marks_audit')),
    comment='Immutable marks change history — never UPDATE or DELETE rows.'
    )
    op.create_index(op.f('ix_marks_audit_exam_id'), 'marks_audit', ['exam_id'], unique=False)
    op.create_index('idx_marks_audit_ess', 'marks_audit', ['exam_student_subject_id', 'paper_type'], unique=False)
    op.create_index('idx_marks_audit_exam', 'marks_audit', ['exam_id', 'station_occurred_at'], unique=False)
    op.create_index('idx_marks_audit_event', 'marks_audit', ['sync_event_id'], unique=False)
    op.create_index('idx_marks_audit_station', 'marks_audit', ['station_id', 'station_occurred_at'], unique=False)
    op.add_column('attendance', sa.Column('station_occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item_marks', sa.Column('station_occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('item_marks', 'writer_source')
    op.alter_column('station_machine_credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('total_marks', sa.Column('station_occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('total_marks', 'writer_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('total_marks', sa.Column('writer_source', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('total_marks', 'station_occurred_at')
    op.alter_column('station_machine_credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('item_marks', sa.Column('writer_source', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('item_marks', 'station_occurred_at')
    op.drop_column('attendance', 'station_occurred_at')
    op.drop_index(op.f('ix_marks_audit_exam_id'), table_name='marks_audit')
    op.drop_index('idx_marks_audit_ess', table_name='marks_audit')
    op.drop_index('idx_marks_audit_exam', table_name='marks_audit')
    op.drop_index('idx_marks_audit_event', table_name='marks_audit')
    op.drop_index('idx_marks_audit_station', table_name='marks_audit')
    op.drop_table('marks_audit')
    # ### end Alembic commands ###
